CREATE DATABASE IF NOT EXISTS MATHBLOG;

USE MATHBLOG;

CREATE TABLE IF NOT EXISTS USER_TABLE(
    ID_USER INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(25),
    EMAIL VARCHAR(60),
    PASSWORD VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CATEGORY(
    ID_CATEGORY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS POST(
    ID_POST INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE_REAL VARCHAR(70),
    TITLE_SEARCH VARCHAR(70),
    LIKES INT,
    VIEWS INT,
    DESC VARCHAR(255),
    TEXT_POST VARCHAR(2000),
    IMG VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS POSTCATEGORY(
    ID_POST INT NOT NULL,
    ID_CATEGORY INT NOT NULL,
    FOREIGN KEY(ID_POST) REFERENCES POST(ID_POST),
    FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
);